// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "MechMovementComponent.generated.h"

/** Movement states for the mech */
UENUM(BlueprintType)
enum class EMoveState : uint8
{
	Idle UMETA(DisplayName = "Idle"),
	Walking UMETA(DisplayName = "Walking"),
	Running UMETA(DisplayName = "Running"),
	Braced UMETA(DisplayName = "Braced"),
	Strafing UMETA(DisplayName = "Strafing"),
	Boosting UMETA(DisplayName = "Boosting"),
	Stumbling UMETA(DisplayName = "Stumbling"),
	Fallen UMETA(DisplayName = "Fallen")
};

/** Terrain types that affect movement */
UENUM(BlueprintType)
enum class ETerrainType : uint8
{
	Stable UMETA(DisplayName = "Stable"),
	Loose UMETA(DisplayName = "Loose"),
	Ice UMETA(DisplayName = "Ice"),
	Lava UMETA(DisplayName = "Lava"),
	Water UMETA(DisplayName = "Water"),
	Hazardous UMETA(DisplayName = "Hazardous")
};

/**
 * Movement component for the player mech
 * Handles locomotion, balance, terrain interaction, and boost mechanics
 */
UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class STEELCATHEDRALS_API UMechMovementComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	// Sets default values for this component's properties
	UMechMovementComponent();

	// Called every frame
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

	// Setup replication
	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

protected:
	// Called when the game starts
	virtual void BeginPlay() override;

public:
	// ============================================================
	// Movement Parameters
	// ============================================================

	/** Maximum walking speed in cm/s */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Movement|Speed")
	float MaxWalkSpeed = 800.0f;

	/** Maximum running speed in cm/s */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Movement|Speed")
	float MaxRunSpeed = 1600.0f;

	/** Boost speed in cm/s */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Movement|Speed")
	float BoostSpeed = 3000.0f;

	/** Turn rate in degrees per second */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Movement|Rotation")
	float TurnRate = 30.0f;

	/** Balance recovery rate (units per second) */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Movement|Balance")
	float BalanceRecoveryRate = 2.0f;

	/** Balance value threshold for stumbling */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Movement|Balance")
	float StumbleThreshold = -0.7f;

	// ============================================================
	// Current State
	// ============================================================

	/** Current speed of the mech */
	UPROPERTY(Replicated, BlueprintReadOnly, Category = "Movement|State")
	float CurrentSpeed = 0.0f;

	/** Balance value from -1.0 (falling backward) to 1.0 (falling forward) */
	UPROPERTY(Replicated, BlueprintReadOnly, Category = "Movement|State")
	float BalanceValue = 0.0f;

	/** Current movement state */
	UPROPERTY(Replicated, BlueprintReadOnly, Category = "Movement|State")
	EMoveState MovementState = EMoveState::Idle;

	/** Current terrain type */
	UPROPERTY(BlueprintReadOnly, Category = "Movement|State")
	ETerrainType CurrentTerrain = ETerrainType::Stable;

	// ============================================================
	// Boost Parameters
	// ============================================================

	/** Duration of boost in seconds */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Movement|Boost")
	float BoostDuration = 1.0f;

	/** Cooldown between boosts in seconds */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Movement|Boost")
	float BoostCooldown = 5.0f;

	/** Heat generated by boost */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Movement|Boost")
	float BoostHeatGeneration = 25.0f;

	/** Remaining boost cooldown time */
	UPROPERTY(BlueprintReadOnly, Category = "Movement|State")
	float BoostCooldownRemaining = 0.0f;

	// ============================================================
	// Input Processing
	// ============================================================

	/** Process forward/backward movement input */
	UFUNCTION(BlueprintCallable, Category = "Movement")
	void ProcessMoveInput(FVector2D InputVector);

	/** Process turning input */
	UFUNCTION(BlueprintCallable, Category = "Movement")
	void ProcessTurnInput(float TurnInput);

	/** Set braced state (locks mech in place for stable shooting) */
	UFUNCTION(BlueprintCallable, Category = "Movement")
	void SetBraced(bool bBraced);

	/** Activate boost in specified direction */
	UFUNCTION(BlueprintCallable, Category = "Movement")
	void ActivateBoost(FVector Direction);

	// ============================================================
	// State Queries
	// ============================================================

	/** Check if mech is currently braced */
	UFUNCTION(BlueprintPure, Category = "Movement")
	bool IsBraced() const;

	/** Check if mech can activate boost */
	UFUNCTION(BlueprintPure, Category = "Movement")
	bool CanBoost() const;

	/** Get current aim stability modifier for weapons (0.0 = unstable, 1.0 = stable) */
	UFUNCTION(BlueprintPure, Category = "Movement")
	float GetAimStabilityModifier() const;

	// ============================================================
	// Terrain Interaction
	// ============================================================

	/** Update current terrain type */
	UFUNCTION(BlueprintCallable, Category = "Movement")
	void UpdateTerrainType(ETerrainType NewTerrain);

	/** Get speed modifier based on current terrain */
	UFUNCTION(BlueprintPure, Category = "Movement")
	float GetTerrainSpeedModifier() const;

	// ============================================================
	// Balance Management
	// ============================================================

	/** Apply disruption to balance (e.g., from taking damage) */
	UFUNCTION(BlueprintCallable, Category = "Movement")
	void ApplyBalanceDisruption(float Magnitude, FVector Direction);

	/** Update balance state */
	void UpdateBalance(float DeltaTime);

	// ============================================================
	// Events
	// ============================================================

	/** Broadcast when movement state changes */
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnMovementStateChanged, EMoveState, NewState);
	UPROPERTY(BlueprintAssignable, Category = "Movement|Events")
	FOnMovementStateChanged OnMovementStateChanged;

	/** Broadcast when mech takes a footstep */
	DECLARE_DYNAMIC_MULTICAST_DELEGATE(FOnFootstep);
	UPROPERTY(BlueprintAssignable, Category = "Movement|Events")
	FOnFootstep OnFootstep;

	/** Broadcast when balance is lost */
	DECLARE_DYNAMIC_MULTICAST_DELEGATE(FOnBalanceLost);
	UPROPERTY(BlueprintAssignable, Category = "Movement|Events")
	FOnBalanceLost OnBalanceLost;

	/** Broadcast when boost is activated */
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnBoostActivated, float, HeatGenerated);
	UPROPERTY(BlueprintAssignable, Category = "Movement|Events")
	FOnBoostActivated OnBoostActivated;

private:
	// Internal state tracking
	EMoveState PreviousMovementState = EMoveState::Idle;
	float FootstepTimer = 0.0f;
	float FootstepInterval = 1.0f; // Time between footsteps
	float MoveForwardInput = 0.0f;
	float TurnInputValue = 0.0f;
	bool bIsBraced = false;
	bool bIsBoostActive = false;
	float BoostTimeRemaining = 0.0f;
	FVector BoostDirection = FVector::ZeroVector;
};
